### ISSUE TITLE
Use keycloak client from new Keycloak instance (auth.ssb.no)

### ISSUE THREAD

**Issue by kschulst** [statisticsnorway/dapla-ctrl#302]
Instead of relying on a oauth2-proxy Keycloak client configured in the legacy Keycloak instance running in BIP, we should create new dapla-ctrl clients in keycloak-iac.

See https://github.com/statisticsnorway/keycloak-iac?tab=readme-ov-file#oauth2-proxy-client

**Comment by skykanin** [comment]
The NAIS deployments of Dapla Ctrl now use the new keycloak instances for prod and test
